# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('field_type', models.PositiveSmallIntegerField(choices=[('String', 1), ('Number', 2), ('Enum', 3)], verbose_name='type')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InsuranceRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='post date')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='risks.Field', verbose_name='select field')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='field',
            name='insurance_risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='risks.InsuranceRisk', verbose_name='insurance risk'),
        ),
    ]
