# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'String'), (2, 'Number'), (3, 'Enum')], verbose_name='type'),
        ),
    ]
