# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20181112_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(max_length=10, verbose_name='type'),
        ),
    ]
