# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20181112_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={},
        ),
    ]
