# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_auto_20181112_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'String'), ('number', 'Number'), ('select', 'Enum')], max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='insurancerisk',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
