# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfield',
            old_name='client_insurance_rik',
            new_name='client_insurance_risk',
        ),
    ]
