# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20181112_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfield',
            options={'ordering': ('field',)},
        ),
        migrations.AlterField(
            model_name='clientfield',
            name='client_insurance_risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='clients.ClientInsuranceRisk', verbose_name='client insurance risk'),
        ),
    ]
