# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20181114_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfield',
            name='select_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='risks.SelectOption', verbose_name='selected option'),
        ),
    ]
